server:
  port: 8401

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  application:
    name: nacos-order-consumer

management:
  endpoints:
    web:
      exposure:
        include: '*'
