server:
  port: 9002

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#      discovery:
#        group: CLOUD_GROUP
  application:
    name: nacos-payment-provider

management:
  endpoints:
    web:
      exposure:
        include: '*'