server:
  port: 9002

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8845,127.0.0.1:8848
#     discovery:
#        group: CLOUD_GROUP
  application:
    name: nacos-payment-provider

management:
  endpoints:
    web:
      exposure:
        include: '*'