server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment #服务名称

eureka:
  client:
    register-with-eureka: on #表示向注册中心注册自己 默认为true
    fetch-registry: on #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/ # 入驻地址
  #      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: on
  #    lease-renewal-interval-in-seconds: 1 # eureka客户端向服务端发送心跳的时间间隔 单位秒 默认30
  #    lease-expiration-duration-in-seconds: 2 # eureka